from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape as html_escape
from typing import Iterable

from jinja2 import Environment
from weasyprint import HTML

from app.models.topology import Topology
from app.schemas.engine_plan import EngineDeploymentPlanSchema
from app.schemas.topology import TopologyBase
from app.services.topology_translator import translate_topology_to_engine_plan


REPORT_HTML_TEMPLATE = """<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ report.title }}</title>
  <style>
    @page { size: A4; margin: 18mm 16mm; }
    body {
      color: #172033;
      font-family: "DejaVu Sans", "Segoe UI", Arial, sans-serif;
      font-size: 10.5pt;
      line-height: 1.35;
    }
    h1 { color: #0f3b5f; font-size: 22pt; margin: 0 0 4pt; }
    h2 {
      border-bottom: 1px solid #c7d2df;
      color: #184c72;
      font-size: 14pt;
      margin: 18pt 0 8pt;
      padding-bottom: 3pt;
    }
    table { border-collapse: collapse; margin: 8pt 0 14pt; width: 100%; }
    th {
      background: #eaf1f7;
      color: #172033;
      font-weight: 700;
    }
    th, td {
      border: 1px solid #b9c7d5;
      padding: 5pt;
      text-align: left;
      vertical-align: top;
    }
    ul { margin: 4pt 0 12pt 18pt; padding: 0; }
    .meta { color: #4d5e70; margin: 0 0 16pt; }
    .empty { color: #687789; font-style: italic; }
    .diagram {
      border: 1px solid #c7d2df;
      border-radius: 6pt;
      margin: 8pt 0 14pt;
      padding: 8pt;
    }
    .diagram svg { display: block; height: auto; max-width: 100%; width: 100%; }
  </style>
</head>
<body>
  <h1>{{ report.title }}</h1>
  <p class="meta">Generated {{ report.generated_at }} by NetSim-Flow.</p>

  <h2>Metadata</h2>
  <ul>
    <li><strong>Topology ID:</strong> {{ report.topology_id }}</li>
    <li><strong>Status:</strong> {{ report.status }}</li>
    <li><strong>Abstraction Level:</strong> {{ report.abstraction_level }}</li>
  </ul>

  <h2>Topology Overview</h2>
  <div class="diagram">{{ report.diagram_svg | safe }}</div>

  <h2>Topology Summary</h2>
  <ul>
    <li><strong>Nodes:</strong> {{ report.node_count }}</li>
    <li><strong>Links:</strong> {{ report.link_count }}</li>
    <li><strong>Protocols:</strong> {{ report.protocols }}</li>
  </ul>

  <h2>Node Inventory</h2>
  {% if report.nodes %}
  <table>
    <thead><tr><th>Label</th><th>Type</th><th>Role</th><th>Protocols</th><th>Loopback</th><th>Vendor</th><th>Platform</th></tr></thead>
    <tbody>
      {% for node in report.nodes %}
      <tr><td>{{ node.label }}</td><td>{{ node.type }}</td><td>{{ node.role }}</td><td>{{ node.protocols }}</td><td>{{ node.loopback }}</td><td>{{ node.vendor }}</td><td>{{ node.platform }}</td></tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="empty">No nodes in this topology.</p>
  {% endif %}

  <h2>Interface / IP Table</h2>
  {% if report.interfaces %}
  <table>
    <thead><tr><th>Node</th><th>Port</th><th>IP</th><th>Subnet</th><th>Peer Node</th><th>Peer Port</th><th>Link</th></tr></thead>
    <tbody>
      {% for interface in report.interfaces %}
      <tr><td>{{ interface.node }}</td><td>{{ interface.port }}</td><td>{{ interface.ip }}</td><td>{{ interface.subnet }}</td><td>{{ interface.peer_node }}</td><td>{{ interface.peer_port }}</td><td>{{ interface.link }}</td></tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="empty">No interfaces derived from links.</p>
  {% endif %}

  <h2>Link Table</h2>
  {% if report.links %}
  <table>
    <thead><tr><th>Link ID</th><th>Source</th><th>Target</th><th>Type</th><th>Subnet</th><th>QoS</th><th>Fault State</th></tr></thead>
    <tbody>
      {% for link in report.links %}
      <tr><td>{{ link.id }}</td><td>{{ link.source }}</td><td>{{ link.target }}</td><td>{{ link.type }}</td><td>{{ link.subnet }}</td><td>{{ link.qos }}</td><td>{{ link.fault_state }}</td></tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="empty">No links in this topology.</p>
  {% endif %}

  <h2>Routing Summary</h2>
  {% if report.routing %}
  <table>
    <thead><tr><th>Node</th><th>Protocols</th><th>OSPF Process</th><th>OSPF Area</th><th>Router ID</th></tr></thead>
    <tbody>
      {% for row in report.routing %}
      <tr><td>{{ row.node }}</td><td>{{ row.protocols }}</td><td>{{ row.process }}</td><td>{{ row.area }}</td><td>{{ row.router_id }}</td></tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="empty">No routing configuration found.</p>
  {% endif %}

  <h2>Validation Checklist</h2>
  <ul>
    {% for item in report.validation %}
    <li>{{ item }}</li>
    {% endfor %}
  </ul>

  <h2>Export Metadata</h2>
  <ul>
    <li><strong>Generated by:</strong> NetSim-Flow</li>
    <li><strong>Report Format:</strong> {{ report.format_label }}</li>
  </ul>
</body>
</html>
"""


@dataclass(frozen=True)
class ReportBundle:
    topology: Topology
    topology_schema: TopologyBase
    plan: EngineDeploymentPlanSchema
    generated_at: str
    diagram_svg: str

    @property
    def protocols(self) -> list[str]:
        return sorted({protocol for node in self.plan.nodes for protocol in node.protocols})


def generate_markdown_report(topology: Topology) -> str:
    bundle = _build_report_bundle(topology)

    sections = [
        f"# NetSim-Flow Report: {topology.name}",
        "",
        "## Metadata",
        "",
        f"- **Topology ID:** {topology.id}",
        f"- **Status:** {topology.status}",
        f"- **Abstraction Level:** {topology.abstraction_level}",
        f"- **Generated:** {bundle.generated_at}",
        "",
        "## Topology Overview",
        "",
        bundle.diagram_svg,
        "",
        "## Topology Summary",
        "",
        f"- **Nodes:** {bundle.plan.nodeCount}",
        f"- **Links:** {bundle.plan.linkCount}",
        f"- **Protocols:** {_csv(bundle.protocols)}",
        "",
        "## Node Inventory",
        "",
        _node_inventory_table(bundle.plan.nodes),
        "",
        "## Interface / IP Table",
        "",
        _interface_table(bundle.plan.nodes),
        "",
        "## Link Table",
        "",
        _link_table(bundle.plan.links),
        "",
        "## Routing Summary",
        "",
        _routing_summary(bundle.topology_schema),
        "",
        "## Validation Checklist",
        "",
        "- [ ] Confirm all required links are present.",
        "- [ ] Confirm all production IP addresses match the intended deployment.",
        "- [ ] Start the simulation and validate reachability.",
        "- [ ] Inject planned failure cases and record expected behavior.",
        "",
        "## Export Metadata",
        "",
        "- **Generated by:** NetSim-Flow",
        "- **Report Format:** Markdown v1",
        "",
    ]
    return "\n".join(sections)


def generate_doc_report(topology: Topology) -> bytes:
    html = _render_report_html(topology, "DOC v1")
    return html.encode("utf-8")


def generate_pdf_report(topology: Topology) -> bytes:
    html = _render_report_html(topology, "PDF v1")
    return HTML(string=html).write_pdf()


def _build_report_bundle(topology: Topology) -> ReportBundle:
    graph = topology.graph_json or {}
    topology_schema = TopologyBase(
        name=topology.name,
        description=topology.description,
        abstractionLevel=topology.abstraction_level,
        status=topology.status,
        nodes=graph.get("nodes", []),
        edges=graph.get("edges", []),
    )
    plan = translate_topology_to_engine_plan(topology_schema)
    generated_at = datetime.now(timezone.utc).isoformat()
    return ReportBundle(
        topology=topology,
        topology_schema=topology_schema,
        plan=plan,
        generated_at=generated_at,
        diagram_svg=_topology_svg(topology_schema),
    )


def _render_report_html(topology: Topology, format_label: str) -> str:
    bundle = _build_report_bundle(topology)
    report = {
        "title": f"NetSim-Flow Report: {topology.name}",
        "generated_at": bundle.generated_at,
        "topology_id": str(topology.id),
        "status": topology.status,
        "abstraction_level": topology.abstraction_level,
        "diagram_svg": bundle.diagram_svg,
        "node_count": bundle.plan.nodeCount,
        "link_count": bundle.plan.linkCount,
        "protocols": _csv(bundle.protocols),
        "nodes": _node_rows(bundle.plan.nodes),
        "interfaces": _interface_rows(bundle.plan.nodes),
        "links": _link_rows(bundle.plan.links),
        "routing": _routing_rows(bundle.topology_schema),
        "validation": [
            "Confirm all required links are present.",
            "Confirm all production IP addresses match the intended deployment.",
            "Start the simulation and validate reachability.",
            "Inject planned failure cases and record expected behavior.",
        ],
        "format_label": format_label,
    }
    environment = Environment(autoescape=True)
    return environment.from_string(REPORT_HTML_TEMPLATE).render(report=report)


def _csv(values: Iterable[str]) -> str:
    items = [value for value in values if value]
    return ", ".join(items) if items else "none"


def _node_inventory_table(nodes) -> str:
    if not nodes:
        return "_No nodes in this topology._"

    rows = [
        "| Label | Type | Role | Protocols | Loopback | Vendor | Platform |",
        "|---|---|---|---|---|---|---|",
    ]
    for node in nodes:
        rows.append(
            "| "
            + " | ".join(
                [
                    node.label,
                    node.baseType,
                    node.role or "-",
                    _csv(node.protocols),
                    node.loopback or "-",
                    node.vendor or "-",
                    node.platform or "-",
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _interface_table(nodes) -> str:
    interfaces = [interface for node in nodes for interface in node.interfaces]
    if not interfaces:
        return "_No interfaces derived from links._"

    rows = [
        "| Node | Port | IP | Subnet | Peer Node | Peer Port | Link |",
        "|---|---|---|---|---|---|---|",
    ]
    for interface in interfaces:
        rows.append(
            "| "
            + " | ".join(
                [
                    interface.nodeId,
                    interface.port,
                    interface.ip or "-",
                    interface.subnet or "-",
                    interface.peerNodeId,
                    interface.peerPort,
                    interface.linkId,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _link_table(links) -> str:
    if not links:
        return "_No links in this topology._"

    rows = [
        "| Link ID | Source | Target | Type | Subnet | QoS | Fault State |",
        "|---|---|---|---|---|---|---|",
    ]
    for link in links:
        rows.append(
            "| "
            + " | ".join(
                [
                    link.id,
                    f"{link.sourceNodeId}:{link.sourcePort}",
                    f"{link.targetNodeId}:{link.targetPort}",
                    link.linkType,
                    link.subnet or "-",
                    _dict_summary(link.qos),
                    _dict_summary(link.faultState),
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _routing_summary(topology: TopologyBase) -> str:
    rows = [
        "| Node | Protocols | OSPF Process | OSPF Area | Router ID |",
        "|---|---|---|---|---|",
    ]
    routing_rows = _routing_rows(topology)
    if not routing_rows:
        return "_No routing configuration found._"

    for row in routing_rows:
        rows.append(
            "| "
            + " | ".join([row["node"], row["protocols"], row["process"], row["area"], row["router_id"]])
            + " |"
        )
    return "\n".join(rows)


def _node_rows(nodes) -> list[dict[str, str]]:
    return [
        {
            "label": node.label,
            "type": node.baseType,
            "role": node.role or "-",
            "protocols": _csv(node.protocols),
            "loopback": node.loopback or "-",
            "vendor": node.vendor or "-",
            "platform": node.platform or "-",
        }
        for node in nodes
    ]


def _interface_rows(nodes) -> list[dict[str, str]]:
    return [
        {
            "node": interface.nodeId,
            "port": interface.port,
            "ip": interface.ip or "-",
            "subnet": interface.subnet or "-",
            "peer_node": interface.peerNodeId,
            "peer_port": interface.peerPort,
            "link": interface.linkId,
        }
        for node in nodes
        for interface in node.interfaces
    ]


def _link_rows(links) -> list[dict[str, str]]:
    return [
        {
            "id": link.id,
            "source": f"{link.sourceNodeId}:{link.sourcePort}",
            "target": f"{link.targetNodeId}:{link.targetPort}",
            "type": link.linkType,
            "subnet": link.subnet or "-",
            "qos": _dict_summary(link.qos),
            "fault_state": _dict_summary(link.faultState),
        }
        for link in links
    ]


def _routing_rows(topology: TopologyBase) -> list[dict[str, str]]:
    rows = []
    for node in topology.nodes:
        logical_config = node.logicalConfig or {}
        routing_config = logical_config.get("routingConfig") or {}
        protocols = node.protocols or []
        if protocols or routing_config:
            rows.append(
                {
                    "node": node.label,
                    "protocols": _csv(protocols),
                    "process": str(routing_config.get("processId", "-")),
                    "area": str(routing_config.get("area", "-")),
                    "router_id": str(routing_config.get("routerId", "-")),
                }
            )
    return rows


def _dict_summary(value: dict | None) -> str:
    if not value:
        return "-"
    summary = ", ".join(f"{key}={item}" for key, item in value.items() if item is not None)
    return summary or "-"


def _topology_svg(topology: TopologyBase) -> str:
    if not topology.nodes:
        return (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 180" role="img" '
            'aria-label="Empty topology diagram">'
            '<rect width="640" height="180" rx="12" fill="#f6f8fb" stroke="#c7d2df"/>'
            '<text x="320" y="96" text-anchor="middle" fill="#687789" '
            'font-family="DejaVu Sans, Arial" font-size="18">Empty topology</text></svg>'
        )

    positions = _scaled_positions(topology)
    width = 760
    height = 420
    node_by_id = {node.id: node for node in topology.nodes}
    parts = [
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
            f'role="img" aria-label="{html_escape(topology.name)} topology diagram">'
        ),
        '<rect width="100%" height="100%" rx="14" fill="#f6f8fb" stroke="#c7d2df"/>',
    ]

    for link in topology.edges:
        if link.sourceNodeId not in positions or link.targetNodeId not in positions:
            continue
        source = positions[link.sourceNodeId]
        target = positions[link.targetNodeId]
        mid_x = (source[0] + target[0]) / 2
        mid_y = (source[1] + target[1]) / 2
        subnet = (link.ipConfig or {}).get("subnet", "")
        stroke = "#d94f4f" if link.faultState and link.faultState.active else "#7b8ea3"
        dash = ' stroke-dasharray="8 5"' if link.faultState and link.faultState.active else ""
        parts.append(
            f'<line x1="{source[0]:.1f}" y1="{source[1]:.1f}" x2="{target[0]:.1f}" '
            f'y2="{target[1]:.1f}" stroke="{stroke}" stroke-width="3"{dash}/>'
        )
        if subnet:
            parts.append(
                f'<text x="{mid_x:.1f}" y="{mid_y - 8:.1f}" text-anchor="middle" '
                'font-family="DejaVu Sans, Arial" font-size="13" fill="#3e5062">'
                f"{html_escape(str(subnet))}</text>"
            )

    for node_id, (x, y) in positions.items():
        node = node_by_id[node_id]
        fill = _node_color(node.baseType)
        parts.extend(
            [
                f'<rect x="{x - 54:.1f}" y="{y - 26:.1f}" width="108" height="52" rx="10" '
                f'fill="{fill}" stroke="#172033" stroke-width="1.4"/>',
                f'<text x="{x:.1f}" y="{y - 4:.1f}" text-anchor="middle" '
                'font-family="DejaVu Sans, Arial" font-size="13" font-weight="700" fill="#ffffff">'
                f"{html_escape(node.label)}</text>",
                f'<text x="{x:.1f}" y="{y + 15:.1f}" text-anchor="middle" '
                'font-family="DejaVu Sans, Arial" font-size="11" fill="#edf4fb">'
                f"{html_escape(node.baseType)}</text>",
            ]
        )

    parts.append("</svg>")
    return "".join(parts)


def _scaled_positions(topology: TopologyBase) -> dict[str, tuple[float, float]]:
    width = 760
    height = 420
    padding_x = 90
    padding_y = 70
    fallback_gap = 130
    raw_positions = {}

    for index, node in enumerate(topology.nodes):
        position = node.position or {}
        x = float(position.get("x", padding_x + (index % 4) * fallback_gap))
        y = float(position.get("y", padding_y + (index // 4) * fallback_gap))
        raw_positions[node.id] = (x, y)

    min_x = min(x for x, _ in raw_positions.values())
    max_x = max(x for x, _ in raw_positions.values())
    min_y = min(y for _, y in raw_positions.values())
    max_y = max(y for _, y in raw_positions.values())
    span_x = max(max_x - min_x, 1)
    span_y = max(max_y - min_y, 1)

    return {
        node_id: (
            padding_x + ((x - min_x) / span_x) * (width - padding_x * 2),
            padding_y + ((y - min_y) / span_y) * (height - padding_y * 2),
        )
        for node_id, (x, y) in raw_positions.items()
    }


def _node_color(base_type: str) -> str:
    return {
        "router": "#2563eb",
        "switch": "#059669",
        "firewall": "#dc2626",
        "cloud": "#64748b",
        "host": "#7c3aed",
        "site": "#0f766e",
    }.get(base_type, "#475569")
