from datetime import datetime, timezone
from html import escape as html_escape
from typing import Iterable

from app.models.topology import Topology
from app.schemas.topology import TopologyBase
from app.services.topology_translator import translate_topology_to_engine_plan


def generate_markdown_report(topology: Topology) -> str:
    graph = topology.graph_json or {}
    topology_schema = TopologyBase(
        name=topology.name,
        description=topology.description,
        abstractionLevel=topology.abstraction_level,
        status=topology.status,
        nodes=graph.get("nodes", []),
        edges=graph.get("edges", []),
    )
    plan = translate_topology_to_engine_plan(topology_schema)
    generated_at = datetime.now(timezone.utc).isoformat()
    protocols = sorted({protocol for node in plan.nodes for protocol in node.protocols})

    sections = [
        f"# NetSim-Flow Report: {topology.name}",
        "",
        "## Metadata",
        "",
        f"- **Topology ID:** {topology.id}",
        f"- **Status:** {topology.status}",
        f"- **Abstraction Level:** {topology.abstraction_level}",
        f"- **Generated:** {generated_at}",
        "",
        "## Topology Summary",
        "",
        f"- **Nodes:** {plan.nodeCount}",
        f"- **Links:** {plan.linkCount}",
        f"- **Protocols:** {_csv(protocols)}",
        "",
        "## Node Inventory",
        "",
        _node_inventory_table(plan.nodes),
        "",
        "## Interface / IP Table",
        "",
        _interface_table(plan.nodes),
        "",
        "## Link Table",
        "",
        _link_table(plan.links),
        "",
        "## Routing Summary",
        "",
        _routing_summary(topology_schema),
        "",
        "## Validation Checklist",
        "",
        "- [ ] Confirm all required links are present.",
        "- [ ] Confirm all production IP addresses match the intended deployment.",
        "- [ ] Start the simulation and validate reachability.",
        "- [ ] Inject planned failure cases and record expected behavior.",
        "",
        "## Export Metadata",
        "",
        "- **Generated by:** NetSim-Flow",
        "- **Report Format:** Markdown v1",
        "",
    ]
    return "\n".join(sections)


def generate_doc_report(topology: Topology) -> bytes:
    graph = topology.graph_json or {}
    topology_schema = TopologyBase(
        name=topology.name,
        description=topology.description,
        abstractionLevel=topology.abstraction_level,
        status=topology.status,
        nodes=graph.get("nodes", []),
        edges=graph.get("edges", []),
    )
    plan = translate_topology_to_engine_plan(topology_schema)
    generated_at = datetime.now(timezone.utc).isoformat()
    protocols = sorted({protocol for node in plan.nodes for protocol in node.protocols})

    html = [
        "<!doctype html>",
        "<html>",
        "<head>",
        '<meta charset="utf-8">',
        f"<title>{html_escape(topology.name)} NetSim-Flow Report</title>",
        "<style>",
        "body { color: #172033; font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.35; }",
        "h1 { color: #0f3b5f; font-size: 22pt; margin-bottom: 4pt; }",
        "h2 { border-bottom: 1px solid #c7d2df; color: #184c72; font-size: 15pt; margin-top: 18pt; padding-bottom: 3pt; }",
        "table { border-collapse: collapse; margin: 8pt 0 14pt; width: 100%; }",
        "th { background: #eaf1f7; color: #172033; font-weight: bold; }",
        "th, td { border: 1px solid #b9c7d5; padding: 5pt; text-align: left; vertical-align: top; }",
        "ul { margin-top: 4pt; }",
        ".meta { color: #4d5e70; margin-bottom: 16pt; }",
        ".empty { color: #687789; font-style: italic; }",
        "</style>",
        "</head>",
        "<body>",
        f"<h1>NetSim-Flow Report: {html_escape(topology.name)}</h1>",
        f'<p class="meta">Generated {html_escape(generated_at)} by NetSim-Flow.</p>',
        "<h2>Metadata</h2>",
        "<ul>",
        f"<li><strong>Topology ID:</strong> {html_escape(str(topology.id))}</li>",
        f"<li><strong>Status:</strong> {html_escape(str(topology.status))}</li>",
        f"<li><strong>Abstraction Level:</strong> {html_escape(str(topology.abstraction_level))}</li>",
        "</ul>",
        "<h2>Topology Summary</h2>",
        "<ul>",
        f"<li><strong>Nodes:</strong> {plan.nodeCount}</li>",
        f"<li><strong>Links:</strong> {plan.linkCount}</li>",
        f"<li><strong>Protocols:</strong> {html_escape(_csv(protocols))}</li>",
        "</ul>",
        "<h2>Node Inventory</h2>",
        _node_inventory_html(plan.nodes),
        "<h2>Interface / IP Table</h2>",
        _interface_html(plan.nodes),
        "<h2>Link Table</h2>",
        _link_html(plan.links),
        "<h2>Routing Summary</h2>",
        _routing_summary_html(topology_schema),
        "<h2>Validation Checklist</h2>",
        "<ul>",
        "<li>Confirm all required links are present.</li>",
        "<li>Confirm all production IP addresses match the intended deployment.</li>",
        "<li>Start the simulation and validate reachability.</li>",
        "<li>Inject planned failure cases and record expected behavior.</li>",
        "</ul>",
        "<h2>Export Metadata</h2>",
        "<ul>",
        "<li><strong>Generated by:</strong> NetSim-Flow</li>",
        "<li><strong>Report Format:</strong> DOC v1</li>",
        "</ul>",
        "</body>",
        "</html>",
    ]
    return "\n".join(html).encode("utf-8")


def generate_pdf_report(topology: Topology) -> bytes:
    lines = _wrap_pdf_lines(_plain_report_lines(topology))
    pages = [lines[index:index + 48] for index in range(0, len(lines), 48)] or [[]]

    objects: list[bytes] = []
    page_object_ids: list[int] = []

    def add_object(content: bytes) -> int:
        objects.append(content)
        return len(objects)

    catalog_id = add_object(b"<< /Type /Catalog /Pages 2 0 R >>")
    pages_id = add_object(b"")
    font_id = add_object(b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>")

    for page_lines in pages:
        stream = _pdf_text_stream(page_lines)
        stream_id = add_object(
            b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n"
            + stream
            + b"\nendstream"
        )
        page_id = add_object(
            b"<< /Type /Page /Parent "
            + str(pages_id).encode("ascii")
            + b" 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 "
            + str(font_id).encode("ascii")
            + b" 0 R >> >> /Contents "
            + str(stream_id).encode("ascii")
            + b" 0 R >>"
        )
        page_object_ids.append(page_id)

    kids = b" ".join(f"{page_id} 0 R".encode("ascii") for page_id in page_object_ids)
    objects[pages_id - 1] = (
        b"<< /Type /Pages /Kids ["
        + kids
        + b"] /Count "
        + str(len(page_object_ids)).encode("ascii")
        + b" >>"
    )

    return _serialize_pdf(objects, catalog_id)


def _csv(values: Iterable[str]) -> str:
    items = [value for value in values if value]
    return ", ".join(items) if items else "none"


def _node_inventory_table(nodes) -> str:
    if not nodes:
        return "_No nodes in this topology._"

    rows = [
        "| Label | Type | Role | Protocols | Loopback | Vendor | Platform |",
        "|---|---|---|---|---|---|---|",
    ]
    for node in nodes:
        rows.append(
            "| "
            + " | ".join(
                [
                    node.label,
                    node.baseType,
                    node.role or "-",
                    _csv(node.protocols),
                    node.loopback or "-",
                    node.vendor or "-",
                    node.platform or "-",
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _interface_table(nodes) -> str:
    interfaces = [interface for node in nodes for interface in node.interfaces]
    if not interfaces:
        return "_No interfaces derived from links._"

    rows = [
        "| Node | Port | IP | Subnet | Peer Node | Peer Port | Link |",
        "|---|---|---|---|---|---|---|",
    ]
    for interface in interfaces:
        rows.append(
            "| "
            + " | ".join(
                [
                    interface.nodeId,
                    interface.port,
                    interface.ip or "-",
                    interface.subnet or "-",
                    interface.peerNodeId,
                    interface.peerPort,
                    interface.linkId,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _link_table(links) -> str:
    if not links:
        return "_No links in this topology._"

    rows = [
        "| Link ID | Source | Target | Type | Subnet | QoS | Fault State |",
        "|---|---|---|---|---|---|---|",
    ]
    for link in links:
        qos = "-"
        if link.qos:
            qos = ", ".join(f"{key}={value}" for key, value in link.qos.items() if value is not None)
            qos = qos or "-"
        fault_state = "-"
        if link.faultState:
            fault_state = ", ".join(
                f"{key}={value}" for key, value in link.faultState.items() if value is not None
            )
            fault_state = fault_state or "-"
        rows.append(
            "| "
            + " | ".join(
                [
                    link.id,
                    f"{link.sourceNodeId}:{link.sourcePort}",
                    f"{link.targetNodeId}:{link.targetPort}",
                    link.linkType,
                    link.subnet or "-",
                    qos,
                    fault_state,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _node_inventory_html(nodes) -> str:
    if not nodes:
        return '<p class="empty">No nodes in this topology.</p>'

    rows = [
        "<table>",
        "<thead><tr><th>Label</th><th>Type</th><th>Role</th><th>Protocols</th><th>Loopback</th><th>Vendor</th><th>Platform</th></tr></thead>",
        "<tbody>",
    ]
    for node in nodes:
        rows.append(
            "<tr>"
            + "".join(
                f"<td>{html_escape(value)}</td>"
                for value in [
                    node.label,
                    node.baseType,
                    node.role or "-",
                    _csv(node.protocols),
                    node.loopback or "-",
                    node.vendor or "-",
                    node.platform or "-",
                ]
            )
            + "</tr>"
        )
    rows.extend(["</tbody>", "</table>"])
    return "\n".join(rows)


def _interface_html(nodes) -> str:
    interfaces = [interface for node in nodes for interface in node.interfaces]
    if not interfaces:
        return '<p class="empty">No interfaces derived from links.</p>'

    rows = [
        "<table>",
        "<thead><tr><th>Node</th><th>Port</th><th>IP</th><th>Subnet</th><th>Peer Node</th><th>Peer Port</th><th>Link</th></tr></thead>",
        "<tbody>",
    ]
    for interface in interfaces:
        rows.append(
            "<tr>"
            + "".join(
                f"<td>{html_escape(value)}</td>"
                for value in [
                    interface.nodeId,
                    interface.port,
                    interface.ip or "-",
                    interface.subnet or "-",
                    interface.peerNodeId,
                    interface.peerPort,
                    interface.linkId,
                ]
            )
            + "</tr>"
        )
    rows.extend(["</tbody>", "</table>"])
    return "\n".join(rows)


def _link_html(links) -> str:
    if not links:
        return '<p class="empty">No links in this topology.</p>'

    rows = [
        "<table>",
        "<thead><tr><th>Link ID</th><th>Source</th><th>Target</th><th>Type</th><th>Subnet</th><th>QoS</th><th>Fault State</th></tr></thead>",
        "<tbody>",
    ]
    for link in links:
        qos = "-"
        if link.qos:
            qos = ", ".join(f"{key}={value}" for key, value in link.qos.items() if value is not None)
            qos = qos or "-"
        fault_state = "-"
        if link.faultState:
            fault_state = ", ".join(
                f"{key}={value}" for key, value in link.faultState.items() if value is not None
            )
            fault_state = fault_state or "-"
        rows.append(
            "<tr>"
            + "".join(
                f"<td>{html_escape(value)}</td>"
                for value in [
                    link.id,
                    f"{link.sourceNodeId}:{link.sourcePort}",
                    f"{link.targetNodeId}:{link.targetPort}",
                    link.linkType,
                    link.subnet or "-",
                    qos,
                    fault_state,
                ]
            )
            + "</tr>"
        )
    rows.extend(["</tbody>", "</table>"])
    return "\n".join(rows)


def _routing_summary(topology: TopologyBase) -> str:
    rows = [
        "| Node | Protocols | OSPF Process | OSPF Area | Router ID |",
        "|---|---|---|---|---|",
    ]
    has_routing = False
    for node in topology.nodes:
        logical_config = node.logicalConfig or {}
        routing_config = logical_config.get("routingConfig") or {}
        protocols = node.protocols or []
        if protocols or routing_config:
            has_routing = True
            rows.append(
                "| "
                + " | ".join(
                    [
                        node.label,
                        _csv(protocols),
                        str(routing_config.get("processId", "-")),
                        str(routing_config.get("area", "-")),
                        str(routing_config.get("routerId", "-")),
                    ]
                )
                + " |"
            )

    return "\n".join(rows) if has_routing else "_No routing configuration found._"


def _routing_summary_html(topology: TopologyBase) -> str:
    rows = [
        "<table>",
        "<thead><tr><th>Node</th><th>Protocols</th><th>OSPF Process</th><th>OSPF Area</th><th>Router ID</th></tr></thead>",
        "<tbody>",
    ]
    has_routing = False
    for node in topology.nodes:
        logical_config = node.logicalConfig or {}
        routing_config = logical_config.get("routingConfig") or {}
        protocols = node.protocols or []
        if protocols or routing_config:
            has_routing = True
            rows.append(
                "<tr>"
                + "".join(
                    f"<td>{html_escape(str(value))}</td>"
                    for value in [
                        node.label,
                        _csv(protocols),
                        routing_config.get("processId", "-"),
                        routing_config.get("area", "-"),
                        routing_config.get("routerId", "-"),
                    ]
                )
                + "</tr>"
            )

    if not has_routing:
        return '<p class="empty">No routing configuration found.</p>'

    rows.extend(["</tbody>", "</table>"])
    return "\n".join(rows)


def _plain_report_lines(topology: Topology) -> list[str]:
    graph = topology.graph_json or {}
    topology_schema = TopologyBase(
        name=topology.name,
        description=topology.description,
        abstractionLevel=topology.abstraction_level,
        status=topology.status,
        nodes=graph.get("nodes", []),
        edges=graph.get("edges", []),
    )
    plan = translate_topology_to_engine_plan(topology_schema)
    generated_at = datetime.now(timezone.utc).isoformat()
    protocols = sorted({protocol for node in plan.nodes for protocol in node.protocols})
    lines = [
        f"NetSim-Flow Report: {topology.name}",
        f"Generated: {generated_at}",
        "",
        "Metadata",
        f"  Topology ID: {topology.id}",
        f"  Status: {topology.status}",
        f"  Abstraction Level: {topology.abstraction_level}",
        "",
        "Topology Summary",
        f"  Nodes: {plan.nodeCount}",
        f"  Links: {plan.linkCount}",
        f"  Protocols: {_csv(protocols)}",
        "",
        "Node Inventory",
    ]
    lines.extend(_plain_node_inventory(plan.nodes))
    lines.extend(["", "Interface / IP Table"])
    lines.extend(_plain_interfaces(plan.nodes))
    lines.extend(["", "Link Table"])
    lines.extend(_plain_links(plan.links))
    lines.extend(["", "Routing Summary"])
    lines.extend(_plain_routing(topology_schema))
    lines.extend(
        [
            "",
            "Validation Checklist",
            "  [ ] Confirm all required links are present.",
            "  [ ] Confirm all production IP addresses match the intended deployment.",
            "  [ ] Start the simulation and validate reachability.",
            "  [ ] Inject planned failure cases and record expected behavior.",
            "",
            "Export Metadata",
            "  Generated by: NetSim-Flow",
            "  Report Format: PDF v1",
        ]
    )
    return lines


def _plain_node_inventory(nodes) -> list[str]:
    if not nodes:
        return ["  No nodes in this topology."]

    lines = ["  Label                 Type       Role       Protocols       Loopback"]
    lines.append("  " + "-" * 74)
    for node in nodes:
        lines.append(
            f"  {node.label[:20]:20}  {node.baseType[:9]:9}  {(node.role or '-')[:9]:9}  "
            f"{_csv(node.protocols)[:14]:14}  {node.loopback or '-'}"
        )
    return lines


def _plain_interfaces(nodes) -> list[str]:
    interfaces = [interface for node in nodes for interface in node.interfaces]
    if not interfaces:
        return ["  No interfaces derived from links."]

    lines = ["  Node                  Port    IP               Subnet           Peer"]
    lines.append("  " + "-" * 82)
    for interface in interfaces:
        peer = f"{interface.peerNodeId}:{interface.peerPort}"
        lines.append(
            f"  {interface.nodeId[:20]:20}  {interface.port[:6]:6}  "
            f"{(interface.ip or '-')[:15]:15}  {(interface.subnet or '-')[:15]:15}  {peer}"
        )
    return lines


def _plain_links(links) -> list[str]:
    if not links:
        return ["  No links in this topology."]

    lines = ["  Link ID               Source                 Target                 Subnet"]
    lines.append("  " + "-" * 86)
    for link in links:
        lines.append(
            f"  {link.id[:20]:20}  {f'{link.sourceNodeId}:{link.sourcePort}'[:20]:20}  "
            f"{f'{link.targetNodeId}:{link.targetPort}'[:20]:20}  {link.subnet or '-'}"
        )
    return lines


def _plain_routing(topology: TopologyBase) -> list[str]:
    lines = []
    for node in topology.nodes:
        logical_config = node.logicalConfig or {}
        routing_config = logical_config.get("routingConfig") or {}
        protocols = node.protocols or []
        if protocols or routing_config:
            lines.append(
                f"  {node.label}: protocols={_csv(protocols)}, "
                f"process={routing_config.get('processId', '-')}, "
                f"area={routing_config.get('area', '-')}, "
                f"router-id={routing_config.get('routerId', '-')}"
            )
    return lines or ["  No routing configuration found."]


def _wrap_pdf_lines(lines: list[str]) -> list[str]:
    wrapped: list[str] = []
    for line in lines:
        safe_line = line if line else " "
        while len(safe_line) > 92:
            wrapped.append(safe_line[:92])
            safe_line = safe_line[92:]
        wrapped.append(safe_line)
    return wrapped


def _pdf_text_stream(lines: list[str]) -> bytes:
    commands = ["BT", "/F1 9 Tf", "50 750 Td", "12 TL"]
    for line in lines:
        commands.append(f"({_escape_pdf_text(line)}) Tj")
        commands.append("T*")
    commands.append("ET")
    return "\n".join(commands).encode("latin-1", errors="replace")


def _escape_pdf_text(text: str) -> str:
    encoded = text.encode("latin-1", errors="replace").decode("latin-1")
    return encoded.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _serialize_pdf(objects: list[bytes], catalog_id: int) -> bytes:
    output = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, content in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{index} 0 obj\n".encode("ascii"))
        output.extend(content)
        output.extend(b"\nendobj\n")

    xref_offset = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.extend(
        b"trailer\n"
        + b"<< /Size "
        + str(len(objects) + 1).encode("ascii")
        + b" /Root "
        + str(catalog_id).encode("ascii")
        + b" 0 R >>\nstartxref\n"
        + str(xref_offset).encode("ascii")
        + b"\n%%EOF\n"
    )
    return bytes(output)
