from datetime import datetime, timezone
from typing import Iterable

from app.models.topology import Topology
from app.schemas.topology import TopologyBase
from app.services.topology_translator import translate_topology_to_engine_plan


def generate_markdown_report(topology: Topology) -> str:
    graph = topology.graph_json or {}
    topology_schema = TopologyBase(
        name=topology.name,
        description=topology.description,
        abstractionLevel=topology.abstraction_level,
        status=topology.status,
        nodes=graph.get("nodes", []),
        edges=graph.get("edges", []),
    )
    plan = translate_topology_to_engine_plan(topology_schema)
    generated_at = datetime.now(timezone.utc).isoformat()
    protocols = sorted({protocol for node in plan.nodes for protocol in node.protocols})

    sections = [
        f"# NetSim-Flow Report: {topology.name}",
        "",
        "## Metadata",
        "",
        f"- **Topology ID:** {topology.id}",
        f"- **Status:** {topology.status}",
        f"- **Abstraction Level:** {topology.abstraction_level}",
        f"- **Generated:** {generated_at}",
        "",
        "## Topology Summary",
        "",
        f"- **Nodes:** {plan.nodeCount}",
        f"- **Links:** {plan.linkCount}",
        f"- **Protocols:** {_csv(protocols)}",
        "",
        "## Node Inventory",
        "",
        _node_inventory_table(plan.nodes),
        "",
        "## Interface / IP Table",
        "",
        _interface_table(plan.nodes),
        "",
        "## Link Table",
        "",
        _link_table(plan.links),
        "",
        "## Routing Summary",
        "",
        _routing_summary(topology_schema),
        "",
        "## Validation Checklist",
        "",
        "- [ ] Confirm all required links are present.",
        "- [ ] Confirm all production IP addresses match the intended deployment.",
        "- [ ] Start the simulation and validate reachability.",
        "- [ ] Inject planned failure cases and record expected behavior.",
        "",
        "## Export Metadata",
        "",
        "- **Generated by:** NetSim-Flow",
        "- **Report Format:** Markdown v1",
        "",
    ]
    return "\n".join(sections)


def _csv(values: Iterable[str]) -> str:
    items = [value for value in values if value]
    return ", ".join(items) if items else "none"


def _node_inventory_table(nodes) -> str:
    if not nodes:
        return "_No nodes in this topology._"

    rows = [
        "| Label | Type | Role | Protocols | Loopback | Vendor | Platform |",
        "|---|---|---|---|---|---|---|",
    ]
    for node in nodes:
        rows.append(
            "| "
            + " | ".join(
                [
                    node.label,
                    node.baseType,
                    node.role or "-",
                    _csv(node.protocols),
                    node.loopback or "-",
                    node.vendor or "-",
                    node.platform or "-",
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _interface_table(nodes) -> str:
    interfaces = [interface for node in nodes for interface in node.interfaces]
    if not interfaces:
        return "_No interfaces derived from links._"

    rows = [
        "| Node | Port | IP | Subnet | Peer Node | Peer Port | Link |",
        "|---|---|---|---|---|---|---|",
    ]
    for interface in interfaces:
        rows.append(
            "| "
            + " | ".join(
                [
                    interface.nodeId,
                    interface.port,
                    interface.ip or "-",
                    interface.subnet or "-",
                    interface.peerNodeId,
                    interface.peerPort,
                    interface.linkId,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _link_table(links) -> str:
    if not links:
        return "_No links in this topology._"

    rows = [
        "| Link ID | Source | Target | Type | Subnet | QoS | Fault State |",
        "|---|---|---|---|---|---|---|",
    ]
    for link in links:
        qos = "-"
        if link.qos:
            qos = ", ".join(f"{key}={value}" for key, value in link.qos.items() if value is not None)
            qos = qos or "-"
        fault_state = "-"
        if link.faultState:
            fault_state = ", ".join(
                f"{key}={value}" for key, value in link.faultState.items() if value is not None
            )
            fault_state = fault_state or "-"
        rows.append(
            "| "
            + " | ".join(
                [
                    link.id,
                    f"{link.sourceNodeId}:{link.sourcePort}",
                    f"{link.targetNodeId}:{link.targetPort}",
                    link.linkType,
                    link.subnet or "-",
                    qos,
                    fault_state,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _routing_summary(topology: TopologyBase) -> str:
    rows = [
        "| Node | Protocols | OSPF Process | OSPF Area | Router ID |",
        "|---|---|---|---|---|",
    ]
    has_routing = False
    for node in topology.nodes:
        logical_config = node.logicalConfig or {}
        routing_config = logical_config.get("routingConfig") or {}
        protocols = node.protocols or []
        if protocols or routing_config:
            has_routing = True
            rows.append(
                "| "
                + " | ".join(
                    [
                        node.label,
                        _csv(protocols),
                        str(routing_config.get("processId", "-")),
                        str(routing_config.get("area", "-")),
                        str(routing_config.get("routerId", "-")),
                    ]
                )
                + " |"
            )

    return "\n".join(rows) if has_routing else "_No routing configuration found._"
